<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotics_description</name>
  <version>2.0.0</version>

  <description>Reusable URDF/Xacro robot descriptions, meshes, and macros for ROS 2</description>

  <maintainer email="eurecat@eurecat.org">jfrascon</maintainer>
  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/jfrascon/robotics_description</url>
  <url type="repository">https://github.com/jfrascon/robotics_description.git</url>
  <url type="bugtracker">https://github.com/jfrascon/robotics_description/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>

  <test_depend>ament_index_python</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>liburdfdom-tools</test_depend>
  <test_depend>xacro</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
