# Example bridge channel for the UM7 IMU.

um7:
  ros_topic_name: um7/data
  gz_topic_name: um7/data
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
  lazy: True
