#!/usr/bin/env python3
"""Generate one open fork tine STL using CadQuery geometry.

This script generates only one tine. The tine uses the same geometry convention
as the open-tines variant generated by `fork_simple_stl_generator.py`.

The tine is modeled as an open shell with four faces:
- top
- left
- right
- rear

The front and the bottom stay open.
"""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    import cadquery as cq
except ImportError as exc:  # pragma: no cover
    raise SystemExit('cadquery is required for this generator. Install it with: pip install cadquery') from exc

# Editable tine dimensions (meters)
tine_len_x = 1.20
tine_len_y = 0.12
tine_len_z = 0.06

# Open-tine wall thickness (meters)
tine_wall_thickness = 0.001


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the open-tine mesh generator."""
    parser = argparse.ArgumentParser(description='Generate one open fork-tine STL using CadQuery geometry.')
    parser.add_argument('--tine-len-x', type=float, default=tine_len_x, help='Tine length in X in m.')
    parser.add_argument('--tine-len-y', type=float, default=tine_len_y, help='Tine width in Y in m.')
    parser.add_argument('--tine-len-z', type=float, default=tine_len_z, help='Tine size in Z in m.')
    parser.add_argument(
        '--wall-thickness',
        type=float,
        default=tine_wall_thickness,
        help='Wall thickness used by the hollow part of the tine in m.',
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=None,
        help='Output STL file path. When omitted, fork_simple_open_tine.stl is used.',
    )
    return parser.parse_args()


def add_box(
    tine: cq.Workplane, x_min: float, x_max: float, y_min: float, y_max: float, z_min: float, z_max: float
) -> cq.Workplane:
    """Union one axis-aligned box into the current CadQuery solid."""
    lx = x_max - x_min
    ly = y_max - y_min
    lz = z_max - z_min
    cx = (x_min + x_max) / 2.0
    cy = (y_min + y_max) / 2.0
    cz = (z_min + z_max) / 2.0
    box = cq.Workplane('XY').box(lx, ly, lz, centered=(True, True, True)).translate((cx, cy, cz))
    return tine.union(box)


def build_open_tine(
    *, tine_len_x_m: float, tine_len_y_m: float, tine_len_z_m: float, wall_thickness_m: float
) -> cq.Shape:
    """Build one centered open tine as a four-face thin-walled shell."""
    x_min = -tine_len_x_m / 2.0
    x_max = tine_len_x_m / 2.0
    y_min = -tine_len_y_m / 2.0
    y_max = tine_len_y_m / 2.0
    z_min = -tine_len_z_m / 2.0
    z_max = tine_len_z_m / 2.0

    inner_y_min = y_min + wall_thickness_m
    inner_y_max = y_max - wall_thickness_m
    inner_z_min = z_min + wall_thickness_m
    inner_z_max = z_max - wall_thickness_m
    rear_face_x_max = x_min + wall_thickness_m

    tine = cq.Workplane('XY')

    # Rear face.
    tine = add_box(tine, x_min, rear_face_x_max, y_min, y_max, z_min, z_max)

    # Top wall.
    tine = add_box(tine, x_min, x_max, y_min, y_max, inner_z_max, z_max)

    # Left and right side walls.
    tine = add_box(tine, x_min, x_max, y_min, inner_y_min, inner_z_min, inner_z_max)
    tine = add_box(tine, x_min, x_max, inner_y_max, y_max, inner_z_min, inner_z_max)
    return tine.val()


def main() -> None:
    """Generate one open tine STL and export it to disk."""
    args = parse_args()
    script_dir = Path(__file__).resolve().parent

    if args.output is None:
        args.output = script_dir.joinpath('fork_simple_open_tine.stl')

    positive_params = {
        'tine_len_x': args.tine_len_x,
        'tine_len_y': args.tine_len_y,
        'tine_len_z': args.tine_len_z,
        'wall_thickness': args.wall_thickness,
    }
    for name, value in positive_params.items():
        if value <= 0.0:
            raise ValueError(f'Invalid argument: {name} must be > 0.0 (got {value}).')

    if 2.0 * args.wall_thickness >= args.tine_len_y:
        raise ValueError('2 * wall_thickness must be smaller than tine_len_y.')

    if 2.0 * args.wall_thickness >= args.tine_len_z:
        raise ValueError('2 * wall_thickness must be smaller than tine_len_z.')

    if args.wall_thickness >= args.tine_len_x:
        raise ValueError('wall_thickness must be smaller than tine_len_x.')

    tine = build_open_tine(
        tine_len_x_m=args.tine_len_x,
        tine_len_y_m=args.tine_len_y,
        tine_len_z_m=args.tine_len_z,
        wall_thickness_m=args.wall_thickness,
    )

    cq.exporters.export(tine, str(args.output))

    print(
        f'Wrote {args.output} '
        f'(args: tine_len_x={args.tine_len_x}, '
        f'tine_len_y={args.tine_len_y}, '
        f'tine_len_z={args.tine_len_z}, '
        f'wall_thickness={args.wall_thickness}, '
        f'output={args.output}).'
    )


if __name__ == '__main__':
    main()
