enabled: True
use_gravity: True
always_on: True
visualize: False
update_rate: 40
hor_fov_deg: { "min_angle": -135, "max_angle": 135 }
hor_res_deg: 0.25
dist_span: { "min_dist": 0.1, "max_dist": 30.0 } # m
gaussian_noise: { "mean": 0, "stddev": 0.01 }
topic: hokuyo_utm30lx/scan
