# Example bridge channel for the Robosense Airy lidar.

robosense_airy:
  ros_topic_name: robosense_airy/scan/points
  gz_topic_name: robosense_airy/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
  lazy: True
