# Example bridge channel for the Robosense Helios 16P lidar.

robosense_helios_16p:
  ros_topic_name: robosense_helios_16p/scan/points
  gz_topic_name: robosense_helios_16p/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
  lazy: True
