enabled: True
use_gravity: True
always_on: True
visualize: False
update_rate: 10
hor_fov_deg: { "min_angle": -180, "max_angle": 180 }
hor_res_deg: 0.2
ver_fov_deg: { "min_angle": -15, "max_angle": 15 }
ver_res_deg: 2
dist_span: { "min_dist": 0.2, "max_dist": 150 } # m
gaussian_noise: { "mean": 0, "stddev": 0.01 }
# The Gazebo plugin will publish two topics:
# Topic <base_topic> with messages of type gz.msgs.LaserScan
# Topic <base_topic>/points with messages of type gz.msgs.PointCloudPacked
base_topic: robosense_helios_16/scan
